# Generated by Django 3.1.3 on 2021-02-11 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pinned', models.BooleanField()),
                ('hf', models.PositiveIntegerField(default=18000)),
                ('lf', models.PositiveIntegerField(default=0)),
                ('nfft_view', models.PositiveIntegerField(default=2048)),
                ('nfft_project', models.PositiveIntegerField(default=2048)),
                ('fft_window_view', models.PositiveIntegerField(default=2048)),
                ('fft_window_project', models.PositiveIntegerField(default=2048)),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=255)),
                ('created', models.PositiveIntegerField()),
                ('created_user', models.PositiveIntegerField()),
                ('last_edit_user', models.PositiveIntegerField()),
            ],
        ),
    ]
