# Generated by Django 3.1.3 on 2021-02-11 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20210211_2353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='pinned',
        ),
    ]
