# Generated by Django 3.1.3 on 2021-02-17 15:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0008_auto_20210217_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='created_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='last_edit_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='last_edit_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
