# Generated by Django 3.1.3 on 2021-02-12 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceContext',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.PositiveIntegerField()),
                ('place_id', models.PositiveIntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='device',
            name='place_id',
        ),
    ]
