# Generated by Django 3.1.3 on 2021-02-12 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_auto_20210212_0044'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicecontext',
            name='device_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
