# Generated by Django 3.1.3 on 2021-02-17 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_auto_20210212_0033'),
        ('projects', '0009_auto_20210217_1526'),
        ('devices', '0003_devicecontext_device_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='recorder_id',
        ),
        migrations.RemoveField(
            model_name='devicecontext',
            name='device_id',
        ),
        migrations.RemoveField(
            model_name='devicecontext',
            name='place_id',
        ),
        migrations.RemoveField(
            model_name='devicecontext',
            name='project_id',
        ),
        migrations.AddField(
            model_name='device',
            name='recorder',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='recorder', to='devices.recorder'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='devicecontext',
            name='device',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='device', to='devices.device'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='devicecontext',
            name='place',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='place', to='places.place'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='devicecontext',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='project', to='projects.project'),
            preserve_default=False,
        ),
    ]
