# Generated by Django 4.0.2 on 2022-02-20 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_auto_20210217_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicecontext',
            name='time_zone',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
