# Generated by Django 4.0.2 on 2022-02-20 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0005_devicecontext_time_zone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='devicecontext',
            old_name='time_zone',
            new_name='timezone',
        ),
    ]
