# Generated by Django 3.1.3 on 2021-02-10 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='de',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='species',
            name='es',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='species',
            name='fr',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='species',
            name='pt',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
