# Generated by Django 3.1.3 on 2021-02-12 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='sample_rate',
            field=models.PositiveIntegerField(default=44100),
            preserve_default=False,
        ),
    ]
