# Generated by Django 3.1.3 on 2021-02-13 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_file_sample_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='stereo',
            field=models.BooleanField(default=False),
        ),
    ]
