# Generated by Django 4.0.2 on 2022-02-20 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0005_file_tz'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='tz',
        ),
    ]
