# Generated by Django 3.0.8 on 2020-08-25 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detections', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detection',
            old_name='analysisid',
            new_name='analysis_id',
        ),
        migrations.RenameField(
            model_name='detection',
            old_name='clusterid',
            new_name='cluster_id',
        ),
        migrations.RenameField(
            model_name='detection',
            old_name='filesid',
            new_name='files_id',
        ),
        migrations.RenameField(
            model_name='detection',
            old_name='labelid',
            new_name='label_id',
        ),
    ]
