# Generated by Django 3.0.8 on 2020-08-31 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detections', '0002_auto_20200825_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='detection',
            name='manual',
            field=models.BooleanField(default=False),
        ),
    ]
